# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.seller_matcher_update import SellerMatcherUpdate

class TestSellerMatcherUpdate(unittest.TestCase):
    """SellerMatcherUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SellerMatcherUpdate:
        """Test SellerMatcherUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SellerMatcherUpdate`
        """
        model = SellerMatcherUpdate()
        if include_optional:
            return SellerMatcherUpdate(
                keywords = [
                    ''
                    ],
                context_pages = [
                    ''
                    ],
                min_max_budget = 1.337,
                min_inspection_rate = 1.337,
                min_purchase_rate = 1.337,
                min_priority = 56,
                buyer_type = '',
                buyer_llm_model = [
                    ''
                    ],
                buyer_system_prompt = [
                    ''
                    ],
                age_limit = 56
            )
        else:
            return SellerMatcherUpdate(
        )
        """

    def testSellerMatcherUpdate(self):
        """Test SellerMatcherUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
