# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.llm_buyer_type import LLMBuyerType

class TestLLMBuyerType(unittest.TestCase):
    """LLMBuyerType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LLMBuyerType:
        """Test LLMBuyerType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LLMBuyerType`
        """
        model = LLMBuyerType()
        if include_optional:
            return LLMBuyerType(
                name = '',
                description = '',
                model = 'openrouter/openai/chatgpt-4o-latest',
                custom_prompt = '',
                max_budget = 1.337
            )
        else:
            return LLMBuyerType(
        )
        """

    def testLLMBuyerType(self):
        """Test LLMBuyerType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
