# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.api.inbox_api import InboxApi


class TestInboxApi(unittest.TestCase):
    """InboxApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InboxApi()

    def tearDown(self) -> None:
        pass

    def test_read_decision_contexts_for_matcher_matchers_matcher_id_inbox_get(self) -> None:
        """Test case for read_decision_contexts_for_matcher_matchers_matcher_id_inbox_get

        Read Decision Contexts For Matcher
        """
        pass

    def test_read_decision_contexts_for_seller_sellers_seller_id_inbox_get(self) -> None:
        """Test case for read_decision_contexts_for_seller_sellers_seller_id_inbox_get

        Read Decision Contexts For Seller
        """
        pass


if __name__ == '__main__':
    unittest.main()
