# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.info_offer_create import InfoOfferCreate

class TestInfoOfferCreate(unittest.TestCase):
    """InfoOfferCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InfoOfferCreate:
        """Test InfoOfferCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InfoOfferCreate`
        """
        model = InfoOfferCreate()
        if include_optional:
            return InfoOfferCreate(
                private_info = '',
                public_info = '',
                price = 1.337
            )
        else:
            return InfoOfferCreate(
                private_info = '',
        )
        """

    def testInfoOfferCreate(self):
        """Test InfoOfferCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
