# coding: utf-8

"""
    Information Market Platform

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.response_read_info_offer_api_questions_context_id_answers_info_offer_id_get import ResponseReadInfoOfferApiQuestionsContextIdAnswersInfoOfferIdGet

class TestResponseReadInfoOfferApiQuestionsContextIdAnswersInfoOfferIdGet(unittest.TestCase):
    """ResponseReadInfoOfferApiQuestionsContextIdAnswersInfoOfferIdGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseReadInfoOfferApiQuestionsContextIdAnswersInfoOfferIdGet:
        """Test ResponseReadInfoOfferApiQuestionsContextIdAnswersInfoOfferIdGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseReadInfoOfferApiQuestionsContextIdAnswersInfoOfferIdGet`
        """
        model = ResponseReadInfoOfferApiQuestionsContextIdAnswersInfoOfferIdGet()
        if include_optional:
            return ResponseReadInfoOfferApiQuestionsContextIdAnswersInfoOfferIdGet(
                id = 56,
                human_seller_id = 56,
                bot_seller_id = 56,
                seller_type = '',
                context_id = 56,
                public_info = '',
                price = 1.337,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                private_info = ''
            )
        else:
            return ResponseReadInfoOfferApiQuestionsContextIdAnswersInfoOfferIdGet(
                id = 56,
                human_seller_id = 56,
                bot_seller_id = 56,
                seller_type = '',
                context_id = 56,
                public_info = '',
                price = 1.337,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                private_info = '',
        )
        """

    def testResponseReadInfoOfferApiQuestionsContextIdAnswersInfoOfferIdGet(self):
        """Test ResponseReadInfoOfferApiQuestionsContextIdAnswersInfoOfferIdGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
