# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_get_users_users_get(self) -> None:
        """Test case for get_users_users_get

        Get Users
        """
        pass

    def test_users_current_user_users_me_get(self) -> None:
        """Test case for users_current_user_users_me_get

        Users:Current User
        """
        pass

    def test_users_delete_user_users_id_delete(self) -> None:
        """Test case for users_delete_user_users_id_delete

        Users:Delete User
        """
        pass

    def test_users_patch_current_user_users_me_patch(self) -> None:
        """Test case for users_patch_current_user_users_me_patch

        Users:Patch Current User
        """
        pass

    def test_users_patch_user_users_id_patch(self) -> None:
        """Test case for users_patch_user_users_id_patch

        Users:Patch User
        """
        pass

    def test_users_user_users_id_get(self) -> None:
        """Test case for users_user_users_id_get

        Users:User
        """
        pass


if __name__ == '__main__':
    unittest.main()
