# coding: utf-8

"""
    Information Market Platform

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.read_info_offers_for_decision_context_api_questions_context_id_answers_get200_response_inner import ReadInfoOffersForDecisionContextApiQuestionsContextIdAnswersGet200ResponseInner

class TestReadInfoOffersForDecisionContextApiQuestionsContextIdAnswersGet200ResponseInner(unittest.TestCase):
    """ReadInfoOffersForDecisionContextApiQuestionsContextIdAnswersGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReadInfoOffersForDecisionContextApiQuestionsContextIdAnswersGet200ResponseInner:
        """Test ReadInfoOffersForDecisionContextApiQuestionsContextIdAnswersGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReadInfoOffersForDecisionContextApiQuestionsContextIdAnswersGet200ResponseInner`
        """
        model = ReadInfoOffersForDecisionContextApiQuestionsContextIdAnswersGet200ResponseInner()
        if include_optional:
            return ReadInfoOffersForDecisionContextApiQuestionsContextIdAnswersGet200ResponseInner(
                id = 56,
                human_seller_id = 56,
                bot_seller_id = 56,
                seller_type = '',
                context_id = 56,
                public_info = '',
                price = 1.337,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                private_info = ''
            )
        else:
            return ReadInfoOffersForDecisionContextApiQuestionsContextIdAnswersGet200ResponseInner(
                id = 56,
                human_seller_id = 56,
                bot_seller_id = 56,
                seller_type = '',
                context_id = 56,
                public_info = '',
                price = 1.337,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                private_info = '',
        )
        """

    def testReadInfoOffersForDecisionContextApiQuestionsContextIdAnswersGet200ResponseInner(self):
        """Test ReadInfoOffersForDecisionContextApiQuestionsContextIdAnswersGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
