# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.human_buyer_read import HumanBuyerRead

class TestHumanBuyerRead(unittest.TestCase):
    """HumanBuyerRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HumanBuyerRead:
        """Test HumanBuyerRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HumanBuyerRead`
        """
        model = HumanBuyerRead()
        if include_optional:
            return HumanBuyerRead(
                user_id = 56,
                default_child_llm = infonomy_client.models.llm_buyer_type.LLMBuyerType(
                    name = '', 
                    description = '', 
                    model = 'openrouter/openai/chatgpt-4o-latest', 
                    custom_prompt = '', 
                    max_budget = 1.337, ),
                default_max_budget = 1.337,
                num_queries = {
                    'key' : 56
                    },
                num_inspected = {
                    'key' : 56
                    },
                num_purchased = {
                    'key' : 56
                    },
                inspection_rate = {
                    'key' : 1.337
                    },
                purchase_rate = {
                    'key' : 1.337
                    }
            )
        else:
            return HumanBuyerRead(
                user_id = 56,
                default_child_llm = infonomy_client.models.llm_buyer_type.LLMBuyerType(
                    name = '', 
                    description = '', 
                    model = 'openrouter/openai/chatgpt-4o-latest', 
                    custom_prompt = '', 
                    max_budget = 1.337, ),
                default_max_budget = 1.337,
                num_queries = {
                    'key' : 56
                    },
                num_inspected = {
                    'key' : 56
                    },
                num_purchased = {
                    'key' : 56
                    },
                inspection_rate = {
                    'key' : 1.337
                    },
                purchase_rate = {
                    'key' : 1.337
                    },
        )
        """

    def testHumanBuyerRead(self):
        """Test HumanBuyerRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
