# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.user_read_private import UserReadPrivate

class TestUserReadPrivate(unittest.TestCase):
    """UserReadPrivate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserReadPrivate:
        """Test UserReadPrivate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserReadPrivate`
        """
        model = UserReadPrivate()
        if include_optional:
            return UserReadPrivate(
                id = 56,
                email = '',
                is_active = True,
                is_superuser = True,
                is_verified = True,
                username = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_login_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                balance = 1.337,
                available_balance = 1.337,
                daily_bonus_amount = 1.337,
                api_keys = {
                    'key' : null
                    }
            )
        else:
            return UserReadPrivate(
                id = 56,
                email = '',
                username = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_login_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                balance = 1.337,
                available_balance = 1.337,
                daily_bonus_amount = 1.337,
                api_keys = {
                    'key' : null
                    },
        )
        """

    def testUserReadPrivate(self):
        """Test UserReadPrivate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
