# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.api.inspection_api import InspectionApi


class TestInspectionApi(unittest.TestCase):
    """InspectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InspectionApi()

    def tearDown(self) -> None:
        pass

    def test_get_job_status_jobs_job_id_status_get(self) -> None:
        """Test case for get_job_status_jobs_job_id_status_get

        Get Job Status
        """
        pass

    def test_inspect_context_questions_context_id_inspect_post(self) -> None:
        """Test case for inspect_context_questions_context_id_inspect_post

        Inspect Context
        """
        pass


if __name__ == '__main__':
    unittest.main()
