# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.body_verify_request_token_auth_request_verify_token_post import BodyVerifyRequestTokenAuthRequestVerifyTokenPost

class TestBodyVerifyRequestTokenAuthRequestVerifyTokenPost(unittest.TestCase):
    """BodyVerifyRequestTokenAuthRequestVerifyTokenPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyVerifyRequestTokenAuthRequestVerifyTokenPost:
        """Test BodyVerifyRequestTokenAuthRequestVerifyTokenPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyVerifyRequestTokenAuthRequestVerifyTokenPost`
        """
        model = BodyVerifyRequestTokenAuthRequestVerifyTokenPost()
        if include_optional:
            return BodyVerifyRequestTokenAuthRequestVerifyTokenPost(
                email = ''
            )
        else:
            return BodyVerifyRequestTokenAuthRequestVerifyTokenPost(
                email = '',
        )
        """

    def testBodyVerifyRequestTokenAuthRequestVerifyTokenPost(self):
        """Test BodyVerifyRequestTokenAuthRequestVerifyTokenPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
