# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.human_seller_read import HumanSellerRead

class TestHumanSellerRead(unittest.TestCase):
    """HumanSellerRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HumanSellerRead:
        """Test HumanSellerRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HumanSellerRead`
        """
        model = HumanSellerRead()
        if include_optional:
            return HumanSellerRead(
                id = 56,
                user_id = 56,
                matchers = [
                    infonomy_client.models.seller_matcher_read.SellerMatcherRead(
                        id = 56, 
                        human_seller_id = 56, 
                        bot_seller_id = 56, 
                        keywords = [
                            ''
                            ], 
                        context_pages = [
                            ''
                            ], 
                        min_max_budget = 1.337, 
                        min_inspection_rate = 1.337, 
                        min_purchase_rate = 1.337, 
                        min_priority = 56, 
                        buyer_type = '', 
                        buyer_llm_model = [
                            ''
                            ], 
                        buyer_system_prompt = [
                            ''
                            ], 
                        age_limit = 56, )
                    ],
                info_offers = [
                    infonomy_client.models.info_offer_read_public.InfoOfferReadPublic(
                        id = 56, 
                        seller_id = 56, 
                        public_info = '', 
                        price = 1.337, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return HumanSellerRead(
                id = 56,
                user_id = 56,
                matchers = [
                    infonomy_client.models.seller_matcher_read.SellerMatcherRead(
                        id = 56, 
                        human_seller_id = 56, 
                        bot_seller_id = 56, 
                        keywords = [
                            ''
                            ], 
                        context_pages = [
                            ''
                            ], 
                        min_max_budget = 1.337, 
                        min_inspection_rate = 1.337, 
                        min_purchase_rate = 1.337, 
                        min_priority = 56, 
                        buyer_type = '', 
                        buyer_llm_model = [
                            ''
                            ], 
                        buyer_system_prompt = [
                            ''
                            ], 
                        age_limit = 56, )
                    ],
                info_offers = [
                    infonomy_client.models.info_offer_read_public.InfoOfferReadPublic(
                        id = 56, 
                        seller_id = 56, 
                        public_info = '', 
                        price = 1.337, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testHumanSellerRead(self):
        """Test HumanSellerRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
