# coding: utf-8

"""
    Information Market Platform

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.api.ui_api import UiApi


class TestUiApi(unittest.TestCase):
    """UiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UiApi()

    def tearDown(self) -> None:
        pass

    def test_create_answer_questions_question_id_answers_post(self) -> None:
        """Test case for create_answer_questions_question_id_answers_post

        Create Answer
        """
        pass

    def test_create_bot_seller_profile_bot_seller_post(self) -> None:
        """Test case for create_bot_seller_profile_bot_seller_post

        Create Bot Seller
        """
        pass

    def test_create_buyer_profile_profile_buyer_post(self) -> None:
        """Test case for create_buyer_profile_profile_buyer_post

        Create Buyer Profile
        """
        pass

    def test_create_matcher_profile_matcher_post(self) -> None:
        """Test case for create_matcher_profile_matcher_post

        Create Matcher
        """
        pass

    def test_create_question_questions_post(self) -> None:
        """Test case for create_question_questions_post

        Create Question
        """
        pass

    def test_home_page_get(self) -> None:
        """Test case for home_page_get

        Home Page
        """
        pass

    def test_inspect_answer_inspect_question_id_answer_id_post(self) -> None:
        """Test case for inspect_answer_inspect_question_id_answer_id_post

        Inspect Answer
        """
        pass

    def test_login_page_login_get(self) -> None:
        """Test case for login_page_login_get

        Login Page
        """
        pass

    def test_question_detail_page_questions_question_id_get(self) -> None:
        """Test case for question_detail_page_questions_question_id_get

        Question Detail Page
        """
        pass

    def test_questions_page_questions_get(self) -> None:
        """Test case for questions_page_questions_get

        Questions Page
        """
        pass

    def test_register_page_register_get(self) -> None:
        """Test case for register_page_register_get

        Register Page
        """
        pass

    def test_update_inbox_status_api_inbox_inbox_id_status_post(self) -> None:
        """Test case for update_inbox_status_api_inbox_inbox_id_status_post

        Update Inbox Status
        """
        pass

    def test_user_profile_page_users_user_id_get(self) -> None:
        """Test case for user_profile_page_users_user_id_get

        User Profile Page
        """
        pass

    def test_users_page_users_get(self) -> None:
        """Test case for users_page_users_get

        Users Page
        """
        pass


if __name__ == '__main__':
    unittest.main()
