# coding: utf-8

"""
    Information Market Platform

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.body_reset_forgot_password_api_auth_forgot_password_post import BodyResetForgotPasswordApiAuthForgotPasswordPost

class TestBodyResetForgotPasswordApiAuthForgotPasswordPost(unittest.TestCase):
    """BodyResetForgotPasswordApiAuthForgotPasswordPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyResetForgotPasswordApiAuthForgotPasswordPost:
        """Test BodyResetForgotPasswordApiAuthForgotPasswordPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyResetForgotPasswordApiAuthForgotPasswordPost`
        """
        model = BodyResetForgotPasswordApiAuthForgotPasswordPost()
        if include_optional:
            return BodyResetForgotPasswordApiAuthForgotPasswordPost(
                email = ''
            )
        else:
            return BodyResetForgotPasswordApiAuthForgotPasswordPost(
                email = '',
        )
        """

    def testBodyResetForgotPasswordApiAuthForgotPasswordPost(self):
        """Test BodyResetForgotPasswordApiAuthForgotPasswordPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
