# coding: utf-8

"""
    Information Market Platform

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.body_reset_reset_password_api_auth_reset_password_post import BodyResetResetPasswordApiAuthResetPasswordPost

class TestBodyResetResetPasswordApiAuthResetPasswordPost(unittest.TestCase):
    """BodyResetResetPasswordApiAuthResetPasswordPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyResetResetPasswordApiAuthResetPasswordPost:
        """Test BodyResetResetPasswordApiAuthResetPasswordPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyResetResetPasswordApiAuthResetPasswordPost`
        """
        model = BodyResetResetPasswordApiAuthResetPasswordPost()
        if include_optional:
            return BodyResetResetPasswordApiAuthResetPasswordPost(
                token = '',
                password = ''
            )
        else:
            return BodyResetResetPasswordApiAuthResetPasswordPost(
                token = '',
                password = '',
        )
        """

    def testBodyResetResetPasswordApiAuthResetPasswordPost(self):
        """Test BodyResetResetPasswordApiAuthResetPasswordPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
