# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.body_reset_forgot_password_auth_forgot_password_post import BodyResetForgotPasswordAuthForgotPasswordPost

class TestBodyResetForgotPasswordAuthForgotPasswordPost(unittest.TestCase):
    """BodyResetForgotPasswordAuthForgotPasswordPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyResetForgotPasswordAuthForgotPasswordPost:
        """Test BodyResetForgotPasswordAuthForgotPasswordPost
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodyResetForgotPasswordAuthForgotPasswordPost`
        """
        model = BodyResetForgotPasswordAuthForgotPasswordPost()
        if include_optional:
            return BodyResetForgotPasswordAuthForgotPasswordPost(
                email = ''
            )
        else:
            return BodyResetForgotPasswordAuthForgotPasswordPost(
                email = '',
        )
        """

    def testBodyResetForgotPasswordAuthForgotPasswordPost(self):
        """Test BodyResetForgotPasswordAuthForgotPasswordPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
