# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.api.decision_contexts_api import DecisionContextsApi


class TestDecisionContextsApi(unittest.TestCase):
    """DecisionContextsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DecisionContextsApi()

    def tearDown(self) -> None:
        pass

    def test_create_decision_context_questions_post(self) -> None:
        """Test case for create_decision_context_questions_post

        Create Decision Context
        """
        pass

    def test_create_info_offer_questions_context_id_answers_post(self) -> None:
        """Test case for create_info_offer_questions_context_id_answers_post

        Create Info Offer
        """
        pass

    def test_delete_decision_context_questions_context_id_delete(self) -> None:
        """Test case for delete_decision_context_questions_context_id_delete

        Delete Decision Context
        """
        pass

    def test_delete_info_offer_questions_context_id_answers_info_offer_id_delete(self) -> None:
        """Test case for delete_info_offer_questions_context_id_answers_info_offer_id_delete

        Delete Info Offer
        """
        pass

    def test_read_decision_context_questions_context_id_get(self) -> None:
        """Test case for read_decision_context_questions_context_id_get

        Read Decision Context
        """
        pass

    def test_read_info_offer_questions_context_id_answers_info_offer_id_get(self) -> None:
        """Test case for read_info_offer_questions_context_id_answers_info_offer_id_get

        Read Info Offer
        """
        pass

    def test_read_info_offers_for_decision_context_questions_context_id_answers_get(self) -> None:
        """Test case for read_info_offers_for_decision_context_questions_context_id_answers_get

        Read Info Offers For Decision Context
        """
        pass

    def test_update_decision_context_questions_context_id_patch(self) -> None:
        """Test case for update_decision_context_questions_context_id_patch

        Update Decision Context
        """
        pass

    def test_update_info_offer_questions_context_id_answers_info_offer_id_patch(self) -> None:
        """Test case for update_info_offer_questions_context_id_answers_info_offer_id_patch

        Update Info Offer
        """
        pass


if __name__ == '__main__':
    unittest.main()
