# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.api.profiles_api import ProfilesApi


class TestProfilesApi(unittest.TestCase):
    """ProfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfilesApi()

    def tearDown(self) -> None:
        pass

    def test_create_human_buyer_buyers_post(self) -> None:
        """Test case for create_human_buyer_buyers_post

        Create Human Buyer
        """
        pass

    def test_create_human_seller_sellers_post(self) -> None:
        """Test case for create_human_seller_sellers_post

        Create Human Seller
        """
        pass

    def test_read_current_human_buyer_buyers_me_get(self) -> None:
        """Test case for read_current_human_buyer_buyers_me_get

        Read Current Human Buyer
        """
        pass

    def test_update_current_human_buyer_buyers_me_put(self) -> None:
        """Test case for update_current_human_buyer_buyers_me_put

        Update Current Human Buyer
        """
        pass


if __name__ == '__main__':
    unittest.main()
