# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.bot_seller_update import BotSellerUpdate

class TestBotSellerUpdate(unittest.TestCase):
    """BotSellerUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BotSellerUpdate:
        """Test BotSellerUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BotSellerUpdate`
        """
        model = BotSellerUpdate()
        if include_optional:
            return BotSellerUpdate(
                info = '',
                price = 1.337,
                llm_model = '',
                llm_prompt = ''
            )
        else:
            return BotSellerUpdate(
        )
        """

    def testBotSellerUpdate(self):
        """Test BotSellerUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
