# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.decision_context_read import DecisionContextRead

class TestDecisionContextRead(unittest.TestCase):
    """DecisionContextRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DecisionContextRead:
        """Test DecisionContextRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DecisionContextRead`
        """
        model = DecisionContextRead()
        if include_optional:
            return DecisionContextRead(
                id = 56,
                query = '',
                context_pages = [
                    ''
                    ],
                buyer_id = 56,
                max_budget = 1.337,
                seller_ids = [
                    56
                    ],
                priority = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                parent = infonomy_client.models.decision_context_read.DecisionContextRead(
                    id = 56, 
                    query = '', 
                    context_pages = [
                        ''
                        ], 
                    buyer_id = 56, 
                    max_budget = 1.337, 
                    seller_ids = [
                        56
                        ], 
                    priority = 56, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    parent = infonomy_client.models.decision_context_read.DecisionContextRead(
                        id = 56, 
                        query = '', 
                        context_pages = [
                            ''
                            ], 
                        buyer_id = 56, 
                        max_budget = 1.337, 
                        seller_ids = [
                            56
                            ], 
                        priority = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        parent = , ), )
            )
        else:
            return DecisionContextRead(
                id = 56,
                query = '',
                context_pages = [
                    ''
                    ],
                buyer_id = 56,
                max_budget = 1.337,
                seller_ids = [
                    56
                    ],
                priority = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                parent = infonomy_client.models.decision_context_read.DecisionContextRead(
                    id = 56, 
                    query = '', 
                    context_pages = [
                        ''
                        ], 
                    buyer_id = 56, 
                    max_budget = 1.337, 
                    seller_ids = [
                        56
                        ], 
                    priority = 56, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    parent = infonomy_client.models.decision_context_read.DecisionContextRead(
                        id = 56, 
                        query = '', 
                        context_pages = [
                            ''
                            ], 
                        buyer_id = 56, 
                        max_budget = 1.337, 
                        seller_ids = [
                            56
                            ], 
                        priority = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        parent = , ), ),
        )
        """

    def testDecisionContextRead(self):
        """Test DecisionContextRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
