# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.api.bot_sellers_api import BotSellersApi


class TestBotSellersApi(unittest.TestCase):
    """BotSellersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BotSellersApi()

    def tearDown(self) -> None:
        pass

    def test_create_bot_seller_bot_sellers_post(self) -> None:
        """Test case for create_bot_seller_bot_sellers_post

        Create Bot Seller
        """
        pass

    def test_create_bot_seller_matcher_bot_sellers_bot_seller_id_matchers_post(self) -> None:
        """Test case for create_bot_seller_matcher_bot_sellers_bot_seller_id_matchers_post

        Create Bot Seller Matcher
        """
        pass

    def test_delete_bot_seller_bot_sellers_bot_seller_id_delete(self) -> None:
        """Test case for delete_bot_seller_bot_sellers_bot_seller_id_delete

        Delete Bot Seller
        """
        pass

    def test_delete_bot_seller_matcher_bot_sellers_bot_seller_id_matchers_matcher_id_delete(self) -> None:
        """Test case for delete_bot_seller_matcher_bot_sellers_bot_seller_id_matchers_matcher_id_delete

        Delete Bot Seller Matcher
        """
        pass

    def test_get_bot_seller_bot_sellers_bot_seller_id_get(self) -> None:
        """Test case for get_bot_seller_bot_sellers_bot_seller_id_get

        Get Bot Seller
        """
        pass

    def test_list_bot_seller_matchers_bot_sellers_bot_seller_id_matchers_get(self) -> None:
        """Test case for list_bot_seller_matchers_bot_sellers_bot_seller_id_matchers_get

        List Bot Seller Matchers
        """
        pass

    def test_list_bot_sellers_bot_sellers_get(self) -> None:
        """Test case for list_bot_sellers_bot_sellers_get

        List Bot Sellers
        """
        pass

    def test_update_bot_seller_bot_sellers_bot_seller_id_put(self) -> None:
        """Test case for update_bot_seller_bot_sellers_bot_seller_id_put

        Update Bot Seller
        """
        pass

    def test_update_bot_seller_matcher_bot_sellers_bot_seller_id_matchers_matcher_id_put(self) -> None:
        """Test case for update_bot_seller_matcher_bot_sellers_bot_seller_id_matchers_matcher_id_put

        Update Bot Seller Matcher
        """
        pass


if __name__ == '__main__':
    unittest.main()
