# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_auth_jwt_login_auth_jwt_login_post(self) -> None:
        """Test case for auth_jwt_login_auth_jwt_login_post

        Auth:Jwt.Login
        """
        pass

    def test_auth_jwt_logout_auth_jwt_logout_post(self) -> None:
        """Test case for auth_jwt_logout_auth_jwt_logout_post

        Auth:Jwt.Logout
        """
        pass

    def test_register_register_auth_register_post(self) -> None:
        """Test case for register_register_auth_register_post

        Register:Register
        """
        pass

    def test_reset_forgot_password_auth_forgot_password_post(self) -> None:
        """Test case for reset_forgot_password_auth_forgot_password_post

        Reset:Forgot Password
        """
        pass

    def test_reset_reset_password_auth_reset_password_post(self) -> None:
        """Test case for reset_reset_password_auth_reset_password_post

        Reset:Reset Password
        """
        pass

    def test_verify_request_token_auth_request_verify_token_post(self) -> None:
        """Test case for verify_request_token_auth_request_verify_token_post

        Verify:Request-Token
        """
        pass

    def test_verify_verify_auth_verify_post(self) -> None:
        """Test case for verify_verify_auth_verify_post

        Verify:Verify
        """
        pass


if __name__ == '__main__':
    unittest.main()
