# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from infonomy_client.models.decision_context_create_non_recursive import DecisionContextCreateNonRecursive

class TestDecisionContextCreateNonRecursive(unittest.TestCase):
    """DecisionContextCreateNonRecursive unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DecisionContextCreateNonRecursive:
        """Test DecisionContextCreateNonRecursive
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DecisionContextCreateNonRecursive`
        """
        model = DecisionContextCreateNonRecursive()
        if include_optional:
            return DecisionContextCreateNonRecursive(
                query = '',
                context_pages = [
                    ''
                    ],
                max_budget = 1.337,
                seller_ids = [
                    56
                    ],
                priority = 56
            )
        else:
            return DecisionContextCreateNonRecursive(
                max_budget = 1.337,
        )
        """

    def testDecisionContextCreateNonRecursive(self):
        """Test DecisionContextCreateNonRecursive"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
