# coding: utf-8

"""
    Q&A Platform API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from infonomy_client.models.llm_buyer_type import LLMBuyerType
from typing import Optional, Set
from typing_extensions import Self

class HumanBuyerRead(BaseModel):
    """
    HumanBuyerRead
    """ # noqa: E501
    id: StrictInt
    default_child_llm: LLMBuyerType
    default_max_budget: Union[StrictFloat, StrictInt]
    num_queries: Dict[str, StrictInt]
    num_inspected: Dict[str, StrictInt]
    num_purchased: Dict[str, StrictInt]
    inspection_rate: Dict[str, Union[StrictFloat, StrictInt]]
    purchase_rate: Dict[str, Union[StrictFloat, StrictInt]]
    __properties: ClassVar[List[str]] = ["id", "default_child_llm", "default_max_budget", "num_queries", "num_inspected", "num_purchased", "inspection_rate", "purchase_rate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HumanBuyerRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of default_child_llm
        if self.default_child_llm:
            _dict['default_child_llm'] = self.default_child_llm.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HumanBuyerRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "default_child_llm": LLMBuyerType.from_dict(obj["default_child_llm"]) if obj.get("default_child_llm") is not None else None,
            "default_max_budget": obj.get("default_max_budget"),
            "num_queries": obj.get("num_queries"),
            "num_inspected": obj.get("num_inspected"),
            "num_purchased": obj.get("num_purchased"),
            "inspection_rate": obj.get("inspection_rate"),
            "purchase_rate": obj.get("purchase_rate")
        })
        return _obj


