# coding: utf-8

"""
    Infonomy

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List
from infonomy_client.models.info_offer_read_public import InfoOfferReadPublic
from infonomy_client.models.seller_matcher_read import SellerMatcherRead
from typing import Optional, Set
from typing_extensions import Self

class HumanSellerRead(BaseModel):
    """
    HumanSellerRead
    """ # noqa: E501
    id: StrictInt
    matchers: List[SellerMatcherRead]
    info_offers: List[InfoOfferReadPublic]
    __properties: ClassVar[List[str]] = ["id", "matchers", "info_offers"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HumanSellerRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in matchers (list)
        _items = []
        if self.matchers:
            for _item_matchers in self.matchers:
                if _item_matchers:
                    _items.append(_item_matchers.to_dict())
            _dict['matchers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in info_offers (list)
        _items = []
        if self.info_offers:
            for _item_info_offers in self.info_offers:
                if _item_info_offers:
                    _items.append(_item_info_offers.to_dict())
            _dict['info_offers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HumanSellerRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "matchers": [SellerMatcherRead.from_dict(_item) for _item in obj["matchers"]] if obj.get("matchers") is not None else None,
            "info_offers": [InfoOfferReadPublic.from_dict(_item) for _item in obj["info_offers"]] if obj.get("info_offers") is not None else None
        })
        return _obj


